import {
  dbCreateCallFollowUp,
  dbCreateLeadBrief,
  dbGetLastLeadBrief,
  dbGetLeadWithContext,
  dbGetNextReminder,
  dbGetRecentActivities,
} from "./db";
import { buildCallFollowupPrompt, buildLeadBriefPrompt, validateLeadAccess } from "./helpers";
import { generateText, Output } from "ai";
import { callFollowUpSchema, leadBriefSchema, SaveCallFollowUpRequest, SaveLeadBriefRequest } from "./schema";
import { CallOutcome } from "../activity";
import { createAIActivity } from "../activity/service";
import { LeadServiceError } from "../lead/service";
import { ActivityType } from "@/generated/prisma/client";
import { Profile } from "@/generated/prisma/client";


export async function generateLeadBrief(
  leadId: string,
  user: Profile,
) {

  
  // Step 1: Fetch the lead, queries the db for the lead with the given leadId
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  // Step 2: Check user permissions
 if (!(await validateLeadAccess(lead.assignedTo?.id, user))) {
    throw new Error("You are not authorized to access this lead");
  }

  // Step 3: Fetch related data 
  // Promise.all runs both queries at the same time to save time
  const [activities, nextReminder] = await Promise.all([
    dbGetRecentActivities(leadId),
    dbGetNextReminder(leadId),
  ]);
  
  // Step 4: Build the AI prompt
  // buildLeadBriefPrompt creates a text prompt that will be sent to the AI model
  const prompt = buildLeadBriefPrompt({
    leadContext: lead,
    recentActivities: activities,
    nextReminder: nextReminder,
  });
  
  // Step 5: Call the AI model
  // generateText is the AI function that creates the lead brief
  const { output } = await generateText({
    // specifies which AI model to use
    model: "deepseek/deepseek-v3.2-thinking",
    // tells the AI to format its output according to the leadBriefSchema 
    output: Output.object({ schema: leadBriefSchema }),
    prompt,
  });

   // Step 6: Save an activity log that the lead brief was generated
  await createAIActivity({
    type: ActivityType.AI_LEAD_BRIEF_GENERATED,
    leadId: leadId,
    actorId: user.id,
    content: `Lead brief generated by ${user.name}`,
  });

  // will be returned to frontend
  return output;

}


export async function saveLeadBrief(
  request: SaveLeadBriefRequest,
  user: Profile,
) {
  const lead = await dbGetLeadWithContext(request.leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user))) {
    throw new Error("You are not authorized to access this lead");
  }

  const brief = await dbCreateLeadBrief(request, user);

  return brief;
}


export async function generateCallFollowup(
  leadId: string,
  callOutcome: CallOutcome,
  agentNotes: string | undefined,
  user: Profile,
) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user))) {
    throw new Error("You are not authorized to access this lead");
  }

  const activities = await dbGetRecentActivities(leadId, 10);

  const prompt = buildCallFollowupPrompt({
    leadContext: lead,
    recentActivities: activities,
    callOutcome,
    agentNotes,
  });

  const { output } = await generateText({
    model: "deepseek/deepseek-v3.2-thinking",
    output: Output.object({ schema: callFollowUpSchema }),
    prompt,
  });

  await createAIActivity({
    type: ActivityType.AI_FOLLOWUP_DRAFT_GENERATED,
    leadId: leadId,
    actorId: user.id,
    content: `Call follow-up generated by ${user.name}`,
  });

  return output;
}


export async function saveCallFollowUp(
  request: SaveCallFollowUpRequest,
  user: Profile,
) {
  const lead = await dbGetLeadWithContext(request.leadId);
  if (!lead) throw new Error("Lead not found");

  if (!(await validateLeadAccess(lead.assignedTo?.id, user))) {
    throw new Error("You are not authorized to access this lead");
  }

  // Save in AILeadBrief table
  const saved = await dbCreateCallFollowUp(request, user);

  // Log activity
  await createAIActivity({
    type: ActivityType.AI_FOLLOWUP_DRAFT_GENERATED,
    leadId: request.leadId,
    actorId: user.id,
    content: `Call follow-up saved by ${user.name}`,
  });

  return saved;
}


export async function getLastLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new LeadServiceError("Lead not found", 404);
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user))) {
    throw new LeadServiceError("Unauthorized", 403);
  }

  const row = await dbGetLastLeadBrief(leadId);
  return row ?? null;
} 

